# Generated by Django 4.0.3 on 2022-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.ImageField(null=True, upload_to='media/cities'),
        ),
    ]
