# Generated by Django 4.1 on 2022-09-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_annonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='date_actu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
