# Generated by Django 4.1 on 2022-09-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_moment_date_actu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annonce',
        ),
    ]
